<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SystemSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // Organization Settings
            [
                'key' => 'org_name',
                'group' => 'organization',
                'value' => 'Climate Action Network Zimbabwe',
                'type' => 'string',
                'description' => 'Organization full name',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_short_name',
                'group' => 'organization',
                'value' => 'CANZIM',
                'type' => 'string',
                'description' => 'Organization acronym',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_logo',
                'group' => 'organization',
                'value' => '/images/logo/canzim_logo.png',
                'type' => 'string',
                'description' => 'Organization logo path',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_address',
                'group' => 'organization',
                'value' => 'Harare, Zimbabwe',
                'type' => 'string',
                'description' => 'Organization physical address',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_phone',
                'group' => 'organization',
                'value' => '+263 XXX XXXX',
                'type' => 'string',
                'description' => 'Organization phone number',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_email',
                'group' => 'organization',
                'value' => 'info@canzimbabwe.org.zw',
                'type' => 'string',
                'description' => 'Organization email',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_website',
                'group' => 'organization',
                'value' => 'https://www.canzimbabwe.org.zw',
                'type' => 'string',
                'description' => 'Organization website',
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Financial Settings
            [
                'key' => 'base_currency',
                'group' => 'financial',
                'value' => 'USD',
                'type' => 'string',
                'description' => 'Base currency code',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'fiscal_year_start_month',
                'group' => 'financial',
                'value' => '1',
                'type' => 'number',
                'description' => 'Fiscal year start month (1-12)',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'date_format',
                'group' => 'financial',
                'value' => 'd/m/Y',
                'type' => 'string',
                'description' => 'Date format (DD/MM/YYYY)',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'datetime_format',
                'group' => 'financial',
                'value' => 'd/m/Y H:i',
                'type' => 'string',
                'description' => 'Datetime format',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Email Settings
            [
                'key' => 'mail_from_address',
                'group' => 'email',
                'value' => 'noreply@canzimbabwe.org.zw',
                'type' => 'string',
                'description' => 'Email sender address',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'mail_from_name',
                'group' => 'email',
                'value' => 'CANZIM FinTrack',
                'type' => 'string',
                'description' => 'Email sender name',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Security Settings
            [
                'key' => 'session_timeout',
                'group' => 'security',
                'value' => '5',
                'type' => 'number',
                'description' => 'Session timeout in minutes',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'password_min_length',
                'group' => 'security',
                'value' => '8',
                'type' => 'number',
                'description' => 'Minimum password length',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'max_login_attempts',
                'group' => 'security',
                'value' => '5',
                'type' => 'number',
                'description' => 'Maximum login attempts before lockout',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'lockout_duration',
                'group' => 'security',
                'value' => '15',
                'type' => 'number',
                'description' => 'Lockout duration in minutes',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Notification Settings (System Defaults)
            [
                'key' => 'notifications_expense_approvals',
                'group' => 'notifications',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'Enable expense approval notifications',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'notifications_budget_alerts',
                'group' => 'notifications',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'Enable budget alert notifications',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'notifications_project_milestones',
                'group' => 'notifications',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'Enable project milestone notifications',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'notifications_comment_mentions',
                'group' => 'notifications',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'Enable comment mention notifications',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'notifications_report_generation',
                'group' => 'notifications',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'Enable report generation notifications',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // General Settings
            [
                'key' => 'timezone',
                'group' => 'general',
                'value' => 'Africa/Harare',
                'type' => 'string',
                'description' => 'System timezone',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'max_file_size_documents',
                'group' => 'general',
                'value' => '5120',
                'type' => 'number',
                'description' => 'Maximum file size for documents in KB (5MB)',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'max_file_size_receipts',
                'group' => 'general',
                'value' => '5120',
                'type' => 'number',
                'description' => 'Maximum file size for receipts in KB (5MB)',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'max_file_size_attachments',
                'group' => 'general',
                'value' => '2048',
                'type' => 'number',
                'description' => 'Maximum file size for comment attachments in KB (2MB)',
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('system_settings')->insert($settings);
    }
}
