<?php

declare(strict_types=1);

namespace App\Services;

use App\Models\Report;
use Barryvdh\DomPDF\Facade\Pdf;
use Carbon\Carbon;
use Illuminate\Support\Facades\Storage;

class ReportPDFService
{
    /**
     * Generate PDF for Budget vs Actual Report.
     */
    public function generateBudgetVsActualPDF(array $data, int $userId): string
    {
        $pdfData = [
            'title' => 'Budget vs Actual Report',
            'organization' => 'Climate Action Network Zimbabwe',
            'report_date' => Carbon::now()->format('F d, Y'),
            'generated_by' => auth()->user()->name ?? 'System',
            'data' => $data,
        ];

        return $this->generateStandardizedPDF('reports.budget-vs-actual', $pdfData, 'budget-vs-actual');
    }

    /**
     * Generate PDF for Cash Flow Report.
     */
    public function generateCashFlowPDF(array $data, int $userId): string
    {
        $pdfData = [
            'title' => 'Cash Flow Report',
            'organization' => 'Climate Action Network Zimbabwe',
            'report_date' => Carbon::now()->format('F d, Y'),
            'generated_by' => auth()->user()->name ?? 'System',
            'data' => $data,
        ];

        return $this->generateStandardizedPDF('reports.cash-flow', $pdfData, 'cash-flow');
    }

    /**
     * Generate PDF for Expense Summary Report.
     */
    public function generateExpenseSummaryPDF(array $data, int $userId): string
    {
        $pdfData = [
            'title' => 'Expense Summary Report',
            'organization' => 'Climate Action Network Zimbabwe',
            'report_date' => Carbon::now()->format('F d, Y'),
            'generated_by' => auth()->user()->name ?? 'System',
            'data' => $data,
        ];

        return $this->generateStandardizedPDF('reports.expense-summary', $pdfData, 'expense-summary');
    }

    /**
     * Generate PDF for Project Status Report.
     */
    public function generateProjectStatusPDF(array $data, int $userId): string
    {
        $pdfData = [
            'title' => 'Project Status Report',
            'organization' => 'Climate Action Network Zimbabwe',
            'report_date' => Carbon::now()->format('F d, Y'),
            'generated_by' => auth()->user()->name ?? 'System',
            'data' => $data,
        ];

        return $this->generateStandardizedPDF('reports.project-status', $pdfData, 'project-status');
    }

    /**
     * Generate PDF for Donor Contributions Report.
     */
    public function generateDonorContributionsPDF(array $data, int $userId): string
    {
        $pdfData = [
            'title' => 'Donor Contributions Report',
            'organization' => 'Climate Action Network Zimbabwe',
            'report_date' => Carbon::now()->format('F d, Y'),
            'generated_by' => auth()->user()->name ?? 'System',
            'data' => $data,
        ];

        return $this->generateStandardizedPDF('reports.donor-contributions', $pdfData, 'donor-contributions');
    }

    /**
     * Generate standardized PDF with CANZIM layout.
     *
     * Header: Logo + Organization + Title
     * Content: Report data
     * Footer: Generated by + Date + Confidentiality + Copyright
     */
    protected function generateStandardizedPDF(string $view, array $data, string $reportType): string
    {
        // Add standardized footer data
        $data['footer'] = [
            'generated_by' => $data['generated_by'],
            'generated_at' => Carbon::now()->format('F d, Y h:i A'),
            'confidentiality' => 'CONFIDENTIAL - For Internal Use Only',
            'copyright' => '© '.Carbon::now()->year.' Climate Action Network Zimbabwe. All Rights Reserved.',
            'developer' => 'Developed with ❤️ by bguvava (bguvava.com)',
        ];

        // Generate PDF
        $pdf = Pdf::loadView($view, $data)
            ->setPaper('a4', 'portrait')
            ->setOption('margin-top', 15)
            ->setOption('margin-bottom', 15)
            ->setOption('margin-left', 15)
            ->setOption('margin-right', 15);

        // Generate unique filename
        $filename = $this->generateFilename($reportType);

        // Store PDF
        $pdfContent = $pdf->output();
        Storage::disk('public')->put("reports/{$filename}", $pdfContent);

        return "reports/{$filename}";
    }

    /**
     * Generate unique filename for report.
     */
    protected function generateFilename(string $reportType): string
    {
        $timestamp = Carbon::now()->format('Ymd-His');
        $randomString = substr(md5(uniqid((string) rand(), true)), 0, 8);

        return "{$reportType}-{$timestamp}-{$randomString}.pdf";
    }

    /**
     * Get PDF download URL.
     */
    public function getDownloadUrl(string $filePath): string
    {
        return Storage::disk('public')->url($filePath);
    }

    /**
     * Delete PDF file.
     */
    public function deletePDF(string $filePath): bool
    {
        if (Storage::disk('public')->exists($filePath)) {
            return Storage::disk('public')->delete($filePath);
        }

        return false;
    }

    /**
     * Get PDF file size in bytes.
     */
    public function getFileSize(string $filePath): ?int
    {
        if (Storage::disk('public')->exists($filePath)) {
            return Storage::disk('public')->size($filePath);
        }

        return null;
    }

    /**
     * Check if PDF exists.
     */
    public function pdfExists(string $filePath): bool
    {
        return Storage::disk('public')->exists($filePath);
    }
}
