{{-- Standardized PDF Footer for CANZIM Reports --}}
<div class="pdf-footer"
    style="position: fixed; bottom: 10px; left: 15px; right: 15px; border-top: 1px solid #E5E7EB; padding-top: 10px; font-size: 9px; color: #6B7280;">
    <table style="width: 100%;">
        <tr>
            <td style="width: 50%; text-align: left; vertical-align: top;">
                <p style="margin: 0; line-height: 1.4;">
                    <strong>Generated by:</strong> {{ $generatedBy }} ({{ $userRole }})<br>
                    <strong>Date & Time:</strong> {{ $generatedAt }}
                </p>
            </td>
            <td style="width: 50%; text-align: right; vertical-align: top;">
                <p style="margin: 0; line-height: 1.4;">
                    <span style="color: #DC2626; font-weight: bold;">CONFIDENTIAL</span> - For Internal Use Only<br>
                    © {{ $year }} {{ $organizationName ?? 'Climate Action Network Zimbabwe' }}. All Rights
                    Reserved.
                </p>
            </td>
        </tr>
        <tr>
            <td colspan="2"
                style="text-align: center; padding-top: 8px; border-top: 1px solid #E5E7EB; margin-top: 5px;">
                <p style="margin: 0; font-size: 8px; color: #9CA3AF;">
                    Developed with ❤️ by <strong>bguvava</strong> (bguvava.com) | Page <span class="pagenum"></span>
                </p>
            </td>
        </tr>
    </table>
</div>
